name: LanternSoulcatcher
m_weight: 1
m_name: $item_soulcatcher_lantern
m_description: "Allows you to collect souls of defeated enemies.  <color=yellow>Souls will only appear if you have this item with you</color>."
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack: 
Secondary_Attack: 
Damage: 
Damage_Per_Level: 
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 42
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 1.5
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: false
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 0
m_knockback: 0
m_useDurability: false
m_useDurabilityDrain: 0
m_durabilityDrain: 0
m_maxDurability: 20
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: None
m_animationState: Shield
m_itemType: Shield
m_toolTier: 0
m_maxQuality: 1
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect: 
