name: JC_Poison_Staff
m_weight: 0.3
m_name: Staff of Myrkr
m_description: This staff smells foul, and so will its victims.  Its special attack is a wild melee swing that can send foes flying, giving the poison time to do its work.
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Projectile
  Attack_Animation: staff_fireball
  Attack_Random_Animation: 0
  Chain_Attacks: 2
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 0
  m_eitrCost: 16
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 0
  RecoilMultiplier: 0
  AttackRange: 2
  AttackHeight: 1.2
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: JC_Staff_Poison_Pro
  Projectile_Vel: 20
  Projectile_Accuraccy: 1
  Projectiles: 1
  Launch_Angle: -4
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: battleaxe_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 2
  Hit_Terrain: true
  Custom_AttackSpeed: 1.5
  m_attackStamina: 16
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.5
  DmgMultiplier: 0
  ForceMultiplier: 500
  StaggerMultiplier: 0
  RecoilMultiplier: 0
  AttackRange: 2.5
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_status_effect: SE_Savheim_Hamstring_Greatbow
  Attack_status_effect_chance: 1
  Attack_Projectile: 
  Projectile_Vel: 20
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    - vfx_clubhit
    - sfx_battleaxe_hit
    - fx_hit_camshake
    - vfx_poisonarrow_hit
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 117
  Slash: 1
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 6
  Slash: 0
  Spirit: 0
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 8
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 1
m_knockback: 1
m_useDurability: true
m_useDurabilityDrain: 0.5
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: ElementalMagic
m_animationState: Staves
m_itemType: TwoHandedWeapon
m_toolTier: 0
m_maxQuality: 3
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect:
  - sfx_bomb_throw
