name: JC_Reaper_Mace
m_weight: 2
m_name: $jc_reaper_mace
m_description: A mace made from a mysterious, otherworldly material that deals 10% bonus damage to world bosses and supports an additional upgrade and socket.
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: swing_longsword
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 11
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2.4
  AttackHeight: 0.8
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Vertical
  Attack_Animation: mace_secondary
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1.4
  m_attackStamina: 22
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.5
  DmgMultiplier: 0.7
  ForceMultiplier: 1
  StaggerMultiplier: 6
  RecoilMultiplier: 0
  AttackRange: 2.5
  AttackHeight: 0.8
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 30
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: fx_swing_camshake
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    - name: sfx_battleaxe_hit
      m_enabled: true
      m_variant: -1
      m_attach: true
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: true
      m_childTransform: ''
    - name: fx_charred_hit
      m_enabled: true
      m_variant: -1
      m_attach: true
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: true
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect:
    - name: sfx_atgeir_attack_secondary
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 155
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Damage_Per_Level:
  Blunt: 9
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.03
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 71
  m_blockPowerPerLevel: 4
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 0
m_useDurability: true
m_useDurabilityDrain: 0.5
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Clubs
m_animationState: OneHanded
m_itemType: OneHandedWeapon
m_toolTier: 0
m_maxQuality: 5
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects:
  - name: vfx_clubhit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_club_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: fx_hit_camshake_knife
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: false
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect:
  - name: sfx_club_swing
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
