name: FistFenrirClaw
m_weight: 2
m_name: $item_fistweapon_fenris
m_description: Claws attack in a frenzy, weaving in savage kicks to knock foes off balance before tearing them to shreds.  They rely on parries to keep them close to their victims.
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: dual_knives
  Attack_Random_Animation: 0
  Chain_Attacks: 2
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 6
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 0.75
  ForceMultiplier: 1
  StaggerMultiplier: 0.5
  RecoilMultiplier: 0
  AttackRange: 2
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 60
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 1
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destory_Previous_Projectile: false
  PerBurst_Resourse_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: sfx_sword_hit
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    - name: vfx_HitSparks
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect:
    - name: sfx_claw_swing
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Burst_Effect: []
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: unarmed_kick
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 12
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 0.5
  ForceMultiplier: 80
  StaggerMultiplier: 12
  RecoilMultiplier: 0
  AttackRange: 2
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 25
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destory_Previous_Projectile: false
  PerBurst_Resourse_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: 
    - name: fx_swing_camshake
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 56
  Spirit: 23
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 3
  Spirit: 1
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: 0
  m_EitrRegen: 0
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 17
  m_blockPowerPerLevel: 1
  m_timedBlockBonus: 6
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 6
m_knockback: 1
m_useDurability: true
m_useDurabilityDrain: 0.25
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Unarmed
m_animationState: Unarmed
m_itemType: TwoHandedWeapon
m_toolTier: 3
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects:
  - name: sfx_unarmed_hit
    m_enabled: true
    m_variant: 0
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hit_Terrain_Effects: []
  Start_Effect:
  - name: sfx_unarmed_swing
    m_enabled: true
    m_variant: 0
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: false
    m_variant: 0
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect: []
