name: JC_Reaper_Pickaxe
m_weight: 2
m_name: $jc_reaper_pickaxe
m_description: "A pickaxe made from a mysterious, otherworldly material that upgrades more strongly than others.  This weapon deals 10% bonus damage to world bosses and surpasses all other pickaxes when it comes to crushing rocks."
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Vertical
  Attack_Animation: swing_pickaxe
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1.2
  m_attackStamina: 5
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1.5
  RecoilMultiplier: 0
  AttackRange: 1.8
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 120
  Attack_Ray_Width: 0.2
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: true
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: greatsword
  Attack_Random_Animation: 0
  Chain_Attacks: 2
  Hit_Terrain: true
  Custom_AttackSpeed: 1.2
  m_attackStamina: 36
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1.5
  RecoilMultiplier: 0
  AttackRange: 1.5
  AttackHeight: 0.6
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: true
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 15
  Frost: 15
  Lightning: 15
  Pickaxe: 98
  Pierce: 15
  Poison: 0
  Slash: 0
  Spirit: 30
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 4
  Frost: 4
  Lightning: 4
  Pickaxe: 10
  Pierce: 4
  Poison: 0
  Slash: 0
  Spirit: 4
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 64
  m_blockPowerPerLevel: 10
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: digg_v3
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 0
m_useDurability: true
m_useDurabilityDrain: 0.5
m_durabilityDrain: 0
m_maxDurability: 400
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Pickaxes
m_animationState: TwoHandedClub
m_itemType: TwoHandedWeapon
m_toolTier: 7
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - sfx_pickaxe_hit
  - vfx_HitSparks
  Hit_Terrain_Effects: 
  Start_Effect:
  - sfx_pickaxe_swing
  Hold_Start_Effects: 
  Trigger_Effect:
  - fx_swing_camshake
  Trail_Effect: 
