Name: SE_Savheim_Brittle
Status_m_name: Brittle
Category: ''
IconName: 
CustomIcon: 
FlashIcon: true
CooldownIcon: false
Tooltip: "Frozen flesh is more likely to shatter and split."
Attributes: None
StartMessageLoc: Center
StartMessage: $se_freezing_start
StopMessageLoc: TopLeft
StopMessage: $se_freezing_stop
RepeatMessageLoc: TopLeft
RepeatMessage: $se_freezing_repeat
RepeatInterval: 60
TimeToLive: 10
StartEffect_: 
StopEffect_: 
StartEffect_PLUS:
- name: vfx_Freezing
  m_enabled: true
  m_variant: -1
  m_attach: true
  m_follow: false
  m_inheritParentRotation: false
  m_inheritParentScale: false
  m_multiplyParentVisualScale: false
  m_randomRotation: false
  m_scale: true
  m_childTransform: ''
StopEffect_PLUS: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 1
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 5
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: 0
  m_jumpStaminaUseModifier: 0
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: None
  m_skillLevelModifier: 0
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods:
  - m_type: Blunt
    m_modifier: Weak
  - m_type: Slash
    m_modifier: Weak
  m_modifyAttackSkill: None
  m_damageModifier: 1
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 0
  m_speedModifier: 0
  m_maxMaxFallSpeed: 0
  m_fallDamageModifier: 0
  m_tickTimer: 0
  m_healthOverTimeTimer: 0
  m_healthOverTimeTicks: 0
  m_healthOverTimeTickHP: 0
