name: SledgeBlackmetal_TW
m_weight: 4
m_name: $sledge_blackmetal_TW
m_description: $sledge_blackmetal_description_TW  Sledges deal massive area effect damage.
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: battleaxe_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 1.2
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2.5
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 0
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects:
    - vfx_HitSparksTW
    - sfx_sledge_lowervolhitTW
    - fx_hit_camshakeTW
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect:
    - fx_swing_camshakeTW
    - sfx_battleaxe_swing_woshTW
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Area
  Attack_Animation: swing_sledge
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 30
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.7
  DmgMultiplier: 1
  ForceMultiplier: 12
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2
  AttackHeight: 0
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 4
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect:
    - sfx_sledge_swingTW
    Trigger_Effect:
    - fx_swing_camshakeTW
    - vfx_sledge_iron_hitTW
    - sfx_sledge_iron_hit_TW
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 90
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 10
  Poison: 0
  Slash: 0
  Spirit: 0
Damage_Per_Level:
  Blunt: 6
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.15
  m_EitrRegen: 0
SE_Equip:
  EffectName: SE_Bash_6_TW
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 49
  m_blockPowerPerLevel: 3
  m_timedBlockBonus: 2
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 2
m_knockback: 10
m_useDurability: true
m_useDurabilityDrain: 0.5
m_durabilityDrain: 0
m_maxDurability: 175
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Clubs
m_animationState: TwoHandedAxe
m_itemType: TwoHandedWeapon
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect: 
