name: JC_Reaper_Crossbow
m_weight: 1.5
m_name: $jc_reaper_crossbow
m_description: "A crossbow made from a mysterious, otherworldly material that deals 10% bonus damage to world bosses."
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Projectile
  Attack_Animation: crossbow_fire
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 0
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 1
  ForceMultiplier: -2
  StaggerMultiplier: 4
  RecoilMultiplier: 0
  AttackRange: 1
  AttackHeight: 1.2
  Spawn_On_Trigger: 
  Requires_Reload: true
  Reload_Animation: reload_crossbow
  ReloadTime: 2.5
  Reload_Stamina_Drain: 1
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 200
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: ''
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 1.5
  AttackHeight: 0.6
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 50
  Frost: 50
  Lightning: 50
  Pickaxe: 0
  Pierce: 50
  Poison: 0
  Slash: 0
  Spirit: 50
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 6
  Frost: 6
  Lightning: 6
  Pickaxe: 0
  Pierce: 6
  Poison: 0
  Slash: 0
  Spirit: 6
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 3
  m_blockPowerPerLevel: 4
  m_timedBlockBonus: 1.5
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 210
m_useDurability: true
m_useDurabilityDrain: 0.5
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0
m_skillType: Crossbows
m_animationState: Crossbow
m_itemType: Bow
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects:
  - sfx_bow_draw
  Trigger_Effect:
  - fx_swing_camshake
  - vfx_jc_crossbow
  - sfx_arbalest_fire
  Trail_Effect: 
